### ISSUE TITLE
[PhoneSnake] latitude and longitude wrong

### ISSUE THREAD

**Issue by BillyBlaze** [PicturElements/picturelements.github.io#1]
latitude and longitude are wrong, it seems like you swapped them around.

i.e. I live in the Netherlands and it says `4.8897,52.374` but should be `52.374,4.8897`

**Comment by PicturElements** [comment]
I noticed that, too. I think I fixed it. Could you try again? I committed about the same time you commented.

**Comment by BillyBlaze** [comment]
Yes :+1:  it's fixed now
